name: Build Proxyscotch

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: proxyscotch

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: checkout
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/v}

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Log into GitHub Container Registry
        run: echo $GITHUB_TOKEN | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Build Docker Image
        run: yarn docker:build

      - id: image
        run: echo ::set-output name=id::ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

      - name: Tag Docker Image
        run: |
          docker tag proxyscotch:latest ${{ steps.image.outputs.id }}:latest
          docker tag proxyscotch:latest ${{ steps.image.outputs.id }}:${{ steps.checkout.outputs.version }}

      - name: Push Docker Image
        run: |
          docker push ${{ steps.image.outputs.id }}:latest
          docker push ${{ steps.image.outputs.id }}:${{ steps.checkout.outputs.version }}

  release:
    name: Build Executable With Electron

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Build/Release App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          build_script_name: 'electron:build'
          args: '--publish=always'
